#!/bin/bash

#tcpdump -r $2 -vttttlen > tmp-tcpdump.dat

#sqlite3 packets-defteros.db '.read ../database/schema.sql'

#./tcpdump2sqlite.pl $1 < tmp-tcpdump.dat

#./sqlite2gv.py $1 > tmp-graph.gv

./sqlite2gv-ip-port.py $1 > tmp-graph-ip-port.gv

ALGO=( dot neato fdp circo twopi )

for algo in ${ALGO[@]} ; do
#	$algo -Tpng -o mac-ip-$algo.png tmp-graph.gv
	$algo -Tpng -o ip-port-$algo.png tmp-graph-ip-port.gv
done
